### ISSUE TITLE
Can I participate in multilingual translation?

### ISSUE THREAD

**Issue by donggu-kang** [storj-archived/storj.io#113]
I am interested in block chains.

I am trying to start a new business with this.
Distributed data storage technology is a representative technology of the block chain, people are focusing too much on virtualization closure.

I am confident that someday these technologies will emerge and grow into everyday life, including major government offices, businesses and individuals.

Very good at Korean. (EN <-> KR)

This technology should be especially famous in Korea.
The cost of storing distributed storage in Korea is too expensive, and many people do not know this technology.

If we release and promote this program in Korean, we will have a lot of users.

I would like to participate in Korean translation.
If possible, add a source for the translation.
I will request a pull.

> As with other sites, it is recommended that you view the country information of your connection IP and automatically display it for your language.

> Because these technologies are not intended to be found by people, the GUI part of a language or community program should be more easily and easily deployed.

> If possible, add another language folder or set of languages for each language. (ex. en - *. js / en - *. js ... etc)

P.S. Really. You can translate Korean fluently and naturally. (ASAP)

**Comment by heunland** [comment]
Hello,
we welcome translations of our materials into other languages. Please join us at https://community.storj.io and ask in the #local channel how you can get involved. Right now, this is an all volunteer effort, we hope to offer bounties for translations soon.
