### ISSUE TITLE
Error in install storj

### ISSUE THREAD

**Issue by selvaraman** [storj-archived/storj.io#118]
I am getting the following error while installing storj. How to resolve this.
ubuntu@ip-:~$ npm install -g storj

> storj@5.0.0 preinstall /home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj
> node ./download.js

Downloading libstorj 
  from: https://github.com/Storj/libstorj/releases/download/v2.0.0-beta/libstorj-2.0.0-beta-linux64.tar.gz 
  to: /home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj/libstorj-2.0.0-beta-linux64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   624    0   624    0     0    419      0 --:--:--  0:00:01 --:--:--   419
100 9717k  100 9717k    0     0   494k      0  0:00:19  0:00:19 --:--:--  928k
Verified libstorj: 
  file: /home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj/libstorj-2.0.0-beta-linux64.tar.gz
  hash: a4d257dfba81836fc409aedab92f2e35c8c25b1910ef82791501fb251774b1b8
Extracting target: /home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj/libstorj-2.0.0-beta-linux64.tar.gz

> storj@5.0.0 install /home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory `/home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj/build'
  CXX(target) Release/obj.target/libstorj/binding.o
../binding.cc: In function ‘void StoreFile(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../binding.cc:475:40: warning: missing initializer for member ‘storj_upload_opts_t::prepare_frame_limit’ [-Wmissing-field-initializers]
     storj_upload_opts_t upload_opts = {};
                                        ^
../binding.cc:475:40: warning: missing initializer for member ‘storj_upload_opts_t::push_frame_limit’ [-Wmissing-field-initializers]
../binding.cc:475:40: warning: missing initializer for member ‘storj_upload_opts_t::push_shard_limit’ [-Wmissing-field-initializers]
../binding.cc:475:40: warning: missing initializer for member ‘storj_upload_opts_t::rs’ [-Wmissing-field-initializers]
../binding.cc:475:40: warning: missing initializer for member ‘storj_upload_opts_t::index’ [-Wmissing-field-initializers]
../binding.cc:475:40: warning: missing initializer for member ‘storj_upload_opts_t::bucket_id’ [-Wmissing-field-initializers]
../binding.cc:475:40: warning: missing initializer for member ‘storj_upload_opts_t::file_name’ [-Wmissing-field-initializers]
../binding.cc:475:40: warning: missing initializer for member ‘storj_upload_opts_t::fd’ [-Wmissing-field-initializers]
../binding.cc: In function ‘void Environment(const v8::FunctionCallbackInfo<v8::Value>&)’:
../binding.cc:811:46: warning: missing initializer for member ‘storj_bridge_options_t::proto’ [-Wmissing-field-initializers]
     storj_bridge_options_t bridge_options = {};
                                              ^
../binding.cc:811:46: warning: missing initializer for member ‘storj_bridge_options_t::host’ [-Wmissing-field-initializers]
../binding.cc:811:46: warning: missing initializer for member ‘storj_bridge_options_t::port’ [-Wmissing-field-initializers]
../binding.cc:811:46: warning: missing initializer for member ‘storj_bridge_options_t::user’ [-Wmissing-field-initializers]
../binding.cc:811:46: warning: missing initializer for member ‘storj_bridge_options_t::pass’ [-Wmissing-field-initializers]
../binding.cc:818:48: warning: missing initializer for member ‘storj_encrypt_options::mnemonic’ [-Wmissing-field-initializers]
     storj_encrypt_options_t encrypt_options = {};
                                                ^
../binding.cc:821:42: warning: missing initializer for member ‘storj_http_options::user_agent’ [-Wmissing-field-initializers]
     storj_http_options_t http_options = {};
                                          ^
../binding.cc:821:42: warning: missing initializer for member ‘storj_http_options::proxy_url’ [-Wmissing-field-initializers]
../binding.cc:821:42: warning: missing initializer for member ‘storj_http_options::cainfo_path’ [-Wmissing-field-initializers]
../binding.cc:821:42: warning: missing initializer for member ‘storj_http_options::low_speed_limit’ [-Wmissing-field-initializers]
../binding.cc:821:42: warning: missing initializer for member ‘storj_http_options::low_speed_time’ [-Wmissing-field-initializers]
../binding.cc:821:42: warning: missing initializer for member ‘storj_http_options::timeout’ [-Wmissing-field-initializers]
../binding.cc:833:47: warning: missing initializer for member ‘storj_log_options::logger’ [-Wmissing-field-initializers]
     static storj_log_options_t log_options = {};
                                               ^
../binding.cc:833:47: warning: missing initializer for member ‘storj_log_options::level’ [-Wmissing-field-initializers]
In file included from ../binding.cc:5:0:
/home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj/libstorj-2.0.0-beta/include/storj.h: At global scope:
/home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj/libstorj-2.0.0-beta/include/storj.h:325:20: warning: ‘BUCKET_OP’ defined but not used [-Wunused-variable]
 static const char *BUCKET_OP[] = { "PUSH", "PULL" };
                    ^
  SOLINK_MODULE(target) Release/obj.target/storj.node
/usr/bin/ld: /home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj/libstorj-2.0.0-beta/depends/lib/libjson-c.a(debug.o): unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/storj.node] Error 1
make: Leaving directory `/home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.13.0-139-generic
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v8.9.4/bin/node" "/home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/.nvm/versions/node/v8.9.4/lib/node_modules/storj
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! storj@5.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the storj@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-01-27T07_45_52_421Z-debug.log

**Comment by super3** [comment]
@selvaraman Look in at [node-libstorj](https://github.com/Storj/node-libstorj) for up to date node bindings.
For command line look here: https://github.com/Storj/libstorj
