### ISSUE TITLE
What is the correct crypto wallet transfer process I need to do?

### ISSUE THREAD

**Issue by CoinKraken** [storj-archived/storj.io#122]
Hi, 
 Can anyone tell me what I need to do to correctly "withdraw" my Storj tokens from an online cryptocurrency trading exchange and deposit them into my  to my wallet IPhone BlockChain.info currency wallet? 
Ok, I purchased some STORJ TOKENS ON THE EXCHANGE market, and I used Bitcoin to make the purchase of the Storj tokens on the trading exchange. 
My purchase order shows ( BTC-STJ /# of Storj shares) I purchased and own in my crypto online exchange market wallet. 
I assume the wallet in the trading exchange is a Bitcoin wallet there's a Bitcoin B on the wallet tab.
I am wanting to transfer my Storj tokens over to my IPhone,app/ BlockChain.info cryptocurrency wallet. My wallet says it will hold Bitcoin or Etherum. 
If I bought the Storj tokens with Bitcoin in the online currency exchange using Bitcoin, what is the correct process that I need to use to withdraw my Storj tokens from the exchange over to my wallet?
 Do I withdraw my Storj tokens from the cryptocurrency online exchange using the BlockChain.info/Bitcoin Address it to my BlockChain.info 
Or do I withdraw the Stroj using the BlockChain Ether Address?
Or do I need to do something totally different to get my Storj tokens into my wallet? 
And clarification on this issues would be a big help, I'm not going to move them till I know what the correct steps are for doing this process because if I don't do the steps required correctly, I will probably lose my Storj tokens all together. 
Anybody had to deal with this type of issue before? What do I do?
Thanks,
Gary

**Comment by nfarah86** [comment]
HI Gary,

This topic is out of scope of what Storj can do. Storj can assist with development, farming, or anything related to the platform. It sounds like you need to submit a request to the exchange you are involved in and get assistance.  Storj is not an exchange or a platform that can discuss token management. How you choose to manage your STORJ tokens is not something Storj can assist.

Nadine

**Comment by heunland** [comment]
Please be advised that the Blockchain.info wallet does NOT support STORJ or any other ERC20 tokens. If you send STORJ tokens to that wallet from an exchange or anywhere else, you will lose access to those tokens. Only use wallets that you hold the private key of yourself, such as myetherwallet.com, Parity or Mist. If you already sent your tokens to a wallet where private keys are not under your own control, you will need to contact their customer support and ask them to assist you in retrieving the STORJ tokens to an address that you control yourself, like is the case with the wallets I mentioned above. If you need more assistance regarding ethereum wallet management for STORJ tokens, please sign up for our rocketchat at https://community.storj.io and ask in the #eth-support channel.

**Comment by CoinKraken** [comment]
Hi Heunland,
   Thanks amillion, myEtherWallet worked prefectly. Thanks for the clear information on what wallets will work, I spent 5-6 hours searching on the various Storj community websites for any article that was even remotely close to discussing which wallets a person can use if they want to purchase Storj. 
 When A person has to figure out where to buy Bitcion(FEE) send it to my bitcoin wallet(FEE)  then to an trading exchange(FEE), where I needed to find out somewhere to convert the bitcoin into Etherum. Never found that, so in the exchange. At that point, I was left wondering if There is Storj with 2 seperate codes, 1 for Bitcoin, 1 for Etherum sold on the Exchanges, will the Stoj even be able to be deposited in any ERC20 wallet if bought with bitcoin? Then Im sitting on Bittrex looking for any Storj (Support, article of any type at all for 3 hours.)
 ((like all the crypto trading exchanges, the Bittrex 5,Star customer support team is so "wicked fast" LOL, at answering questions, they just now replied to my question 78 days ago. Back when I originally wanted to buy Storj tokens. I was asking them what wallet I can use to Hold Storj tokens )) so I have 0% faith in any trading exchanges CS team. And before I ever considered trying to send my Storj tokens to any address in any wallet, (blockchain.info wallets claim to accept Etherum now, but I didnt trust trying until someone with solid Knowledge on the wallet subject replied to me regarding, my conundrum. 
Your information is invaluable to a older person thats not computer savey, the snip that replied above your reply needs to be enlightened that commits like hers have no place in any new cryptocommunity. The people looking to invest in crypto need EASYTO: READ, FOLLOW, FIND, USE, DIRECTIONS, EXAMPLES, ETC.......... The scores that investors are being taught to look at before investing in a coin recieves is based on those type plus other factors and that is the one big thing Storj is currently lacking. Ive probably searched no less than 14-20 hours of my time trying to figure out A.) where and how to buy Storj Tokens, B.) A wallet to keep my storj in, C.) a Storj help website that answers all those questions and all the other questions I tried to findout information about that I never found. 
  When I compare the experience I had with Storj, with the other cryptocion I invested in, ZenCash, it took me under 2 hours and I was done buying my Zencash. The Storj community really needs to focus getting something posted at Storj.io or .com that is written by a noncoder, for a noncoder minded person that is easy to read, clearly points to the help your looking for, and outlines every process for every investor. I started trying to buy Stroj tokens during their ICO, thanks to your help, TONIGHT I finally completed the process and have my Storj token in my wallet. Once again, thank you for you invaluable 411.

**Comment by nfarah86** [comment]
Thanks @heunland . @CoinKraken We are currently working on redoing our whole website and onboarding experience. It's active as of now. In terms of purchasing tokens and onboarding, we are currently developing material that makes its easier for you to do this. We're sorry it took you awhile and I'm really glad @heunland was there to help. Give us a few months to get this in place. Our goal is to really focus on community and ensuring all your needs are met. Thanks for being patient.
