### ISSUE TITLE
Feature: Redirect to partner home page when clicking on name in partner bar.

### ISSUE THREAD

**Issue by MeijeSibbel** [storj-archived/storj.io#152]
It would be nice if the user is re-directed to the partner's home page when clicking on their name in the partner bar. 

![45966397-4a735800-c02b-11e8-94c5-d8c2e5eabd93](https://user-images.githubusercontent.com/11735738/45966609-df765100-c02b-11e8-9cb7-71a44581c9d4.png)

**Comment by chainchompa** [comment]
https://github.com/storj/storj.io/pull/165
