### ISSUE TITLE
Waitlist subscription problem

### ISSUE THREAD

**Issue by sgrunt91** [storj-archived/storj.io#159]
Hello,

I've tried to subscribe to your waitlist, but the final step doesn't work for me.
I've filled the form, and received the email to finish subscription. 
But when I'm going to the link it's always the page https://storj.io/sign-up-success :
```
Almost there!

Check your email and click to confirm you’ve joined the waitlist.

```
So I'm in a loop...
I don't know if my subscription really worked BTW.

Thanks if you have time to check that

**Comment by fuskovic** [comment]
This issue has been resolved. Please try again. You will still need to double-opt in(confirm in your email) but this time you should be redirected to a page notifying you of successfully joining the list with the option to be redirected to our website or manage your subscription preferences. Please try now and confirm.

**Comment by jri-sp** [comment]
Yes it's ok now! 
Thanks a lot

**Comment by sgrunt91** [comment]
Yes it's working now!
Thanks a lot

**Comment by fuskovic** [comment]
My pleasure. Thanks for joining our waitlist. Have a great day!
