### ISSUE TITLE
suggestion - Try to add Storj to the software manager on linux. It would be an easy way for non-coders like myself to install Storj and it would greatly help promote Storj.

### ISSUE THREAD

**Issue by Snarkly** [storj-archived/storj.io#20]
![softwaremanager2](https://cloud.githubusercontent.com/assets/8492776/15260263/c9ab3338-1923-11e6-8337-02393cbd82ec.png)

**Comment by 161chihuahuas** [comment]
Once we get a little closer to a stable release, we will submit to the Debian repositories which should make the packages available to Debian based distros. If we don't make it before the next freeze, we can host our own repository in the meantime.

**Comment by super3** [comment]
@Snarkly Already planning to do this, so closing. Thanks for the suggestion.
