### ISSUE TITLE
Website looks compromised

### ISSUE THREAD

**Issue by littleskunk** [storj-archived/storj.io#29]
Bitcoin users are very carefull. Some of them will check the team page for already know scammers. On https://storj.io/team.html they will find a link that looks compromised. https://storj.io/img/team/gordon-htp.gif

One user reported this on intercom. I am not sure what to. Lucky for me I only have to report this. You have to decide.

**Comment by 161chihuahuas** [comment]
Yeah I put that there because it's funny.

**Comment by 161chihuahuas** [comment]
I think we can live with one user without a sense of humor. :P

**Comment by super3** [comment]
@bookchin I agree.

**Comment by 161chihuahuas** [comment]
Maybe next I will change my name to a ? And link it to:

![](https://media4.giphy.com/media/P5wPrhzZDdeJW/giphy.gif)

:)

**Comment by 161chihuahuas** [comment]
Actually the team page itself should just link to that gif. Lol

**Comment by prestwich** [comment]
Proposal: change company name to Setec Astronomy.

![](http://i.imgur.com/vKoBYgt.gif)
