### ISSUE TITLE
Confusing URLs 

### ISSUE THREAD

**Issue by ordtrogen** [storj-archived/storj.io#39]
These two URLs both work and seem to have the same contents. Or do they? I think it would be less confusing if there were only one URL for the docs section of the site

https://docs.storj.io/v1.0/docs
https://docs.storj.io/docs/

(I don't see the docs section here on github, but didn't know where else to report the "issue")

**Comment by boshevski** [comment]
@ordtrogen it's basically the same, but where do you see the v1.0 link? https://docs.storj.io/v1.0/docs

**Comment by ordtrogen** [comment]
I guessed they'd be the same. 

I'm not sure where I got the 1.0 URL from. I have been managing my Storj installation for 6+ months and have collected notes from various channels like the Rocket+ (ex Slack) forum, Reddit etc. Today I was doing some maintenance and needed the docs and by chance discovered both URLs work and thought I'd point it out.

**Comment by boshevski** [comment]
Thanks for pointing out. We are in the process of updating the documentation and switching to another solution, so this won't be an issue anymore.
