### ISSUE TITLE
Correct info about Free tier limits on website or make to 3GB is real file size limit not File size + addition upload data.

### ISSUE THREAD

**Issue by Jurisg** [storj-archived/storj.io#90]
https://www.reddit.com/r/storj/comments/6zhq6d/suggestion_increase_the_free_space_offering/
My response
Free tier is FREE. Ok they need change info on site what about free tier limitations as if you upload 1GB=1073741824b + 67108864b (encryption)=1744830464b=1.67gb what you need to upload. So yea need change to size include encryption part too on website. But for paying customer its No limits they getting full 25GB storage without limits for 1 year for free.

**Comment by MeijeSibbel** [comment]
related to https://github.com/Storj/bridge/issues/505
