### ISSUE TITLE
Collectd & influxdb syslog errors due to errounous HowTo

### ISSUE THREAD

**Issue by chymian** [storj-archived/storj.io#96]
when following the HowTo:  
https://docs.storj.io/docs/setting-up-storj-share-on-a-raspberry-pi  
the collectd throws errors like:
```
Sep 25 18:31:45 storj collectd[1861]: -1 1 Type `contracts' isn't defined.
Sep 25 18:31:45 storj collectd[1861]: -1 1 Type `delta' isn't defined.
Sep 25 18:31:45 storj collectd[1861]: -1 1 Type `percentused' isn't defined.
```
adding this 3 lines to ```/usr/share/collectd/types.db```
```
contracts               value:GAUGE:0:U
delta                   value:GAUGE:0:U
percentused             value:GAUGE:0:100
```
like the owner has stated (https://github.com/bobey/storj-collectd-plugin), resolves this issue and brings up another one:
```
Sep 25 18:36:24 storj influxd[1745]: 2017/09/25 18:36:24 unable to find "contracts" in TypesDB
Sep 25 18:36:24 storj influxd[1745]: 2017/09/25 18:36:24 unable to find "delta" in TypesDB
Sep 25 18:36:24 storj influxd[1745]: 2017/09/25 18:36:24 unable to find "percentused" in TypesDB
```
This is due to the ```typesdb``` definition in ```/etc/influxdb/influxdb.conf```
the correct entry should look like:  
```
[[collectd]]
  enabled = true
  bind-address = ":25826"
  database = "collectd_db"
  typesdb = "/usr/share/collectd/"
```

Please correct the HowTo

**Comment by super3** [comment]
@chymian Hope you able to get your issue solved. This is the repo for the website, so not the correct place for that type of issue.
